// Ahadu Café — Shared Menu Data
const MENU = [
  { id:1,  cat:'burger', featured:true,  name:'Signature Beef Burger',  desc:'Double flame-grilled beef patty, aged cheddar, caramelized onion & legendary smoky house sauce', price:500, tag:'⭐ #1 Bestseller', img:'https://images.pexels.com/photos/1639565/pexels-photo-1639565.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🥩',n:'Beef patty x2'},{e:'🧀',n:'Aged cheddar'},{e:'🥬',n:'Fresh lettuce'},{e:'🍅',n:'Tomato'},{e:'🧅',n:'Caramelized onion'},{e:'🍞',n:'Brioche bun'},{e:'🥫',n:'Secret sauce'},{e:'🥒',n:'Pickles'}], extras:[{n:'Extra patty',p:80},{n:'Extra cheese',p:40},{n:'Bacon strips',p:60},{n:'Fried egg',p:30}] },
  { id:2,  cat:'burger', featured:false, name:'Crispy Chicken Burger',  desc:'Crunchy golden fried chicken breast, coleslaw, jalapeño mayo & pickled onions', price:380, tag:'🔥 Fan Favorite', img:'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍗',n:'Crispy chicken'},{e:'🥬',n:'Coleslaw'},{e:'🌶',n:'Jalapeño mayo'},{e:'🧅',n:'Pickled onions'},{e:'🍞',n:'Sesame bun'},{e:'🥒',n:'Pickles'}], extras:[{n:'Extra chicken',p:70},{n:'Add cheddar',p:40},{n:'Double jalapeño',p:20}] },
  { id:3,  cat:'burger', featured:false, name:'Mushroom Swiss Burger',  desc:'Juicy beef patty, wild sautéed mushrooms, melted Swiss cheese & truffle aioli', price:440, tag:'🍄 Chef\'s Pick', img:'https://images.pexels.com/photos/2282532/pexels-photo-2282532.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🥩',n:'Beef patty'},{e:'🍄',n:'Wild mushrooms'},{e:'🧀',n:'Swiss cheese'},{e:'🧄',n:'Truffle aioli'},{e:'🥬',n:'Rocket'},{e:'🍞',n:'Toasted bun'}], extras:[{n:'Extra mushrooms',p:40},{n:'Double patty',p:80},{n:'Extra truffle',p:50}] },
  { id:4,  cat:'burger', featured:false, name:'Classic Smash Burger',   desc:'Two thin smashed patties, American cheese, mustard, ketchup & shredded lettuce', price:350, tag:'🍔 Classic', img:'https://images.pexels.com/photos/3219547/pexels-photo-3219547.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🥩',n:'Smashed patty x2'},{e:'🧀',n:'American cheese'},{e:'🥬',n:'Shredded lettuce'},{e:'🍅',n:'Tomato'},{e:'🍞',n:'Potato bun'},{e:'🥫',n:'Mustard & ketchup'}], extras:[{n:'Third patty',p:60},{n:'Caramelized onion',p:30},{n:'Bacon',p:60}] },
  { id:5,  cat:'pizza',  featured:false, name:'Beef & Pepperoni Pizza', desc:'Rich tomato base, spiced ground beef, pepperoni, mozzarella & roasted peppers', price:550, tag:'🍕 Most Ordered', img:'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍕',n:'Pizza dough'},{e:'🍅',n:'Tomato sauce'},{e:'🥩',n:'Ground beef'},{e:'🍖',n:'Pepperoni'},{e:'🧀',n:'Mozzarella'},{e:'🫑',n:'Bell peppers'},{e:'🧅',n:'Red onion'},{e:'🫒',n:'Black olives'}], extras:[{n:'Extra cheese',p:50},{n:'Extra beef',p:70},{n:'Stuffed crust',p:60},{n:'Chilli flakes',p:10}] },
  { id:6,  cat:'pizza',  featured:false, name:'Margherita Pizza',       desc:'Classic San Marzano tomato, buffalo mozzarella, fresh basil & olive oil', price:420, tag:'🌿 Vegetarian', img:'https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍕',n:'Dough'},{e:'🍅',n:'San Marzano tomato'},{e:'🧀',n:'Buffalo mozzarella'},{e:'🌿',n:'Fresh basil'},{e:'🫒',n:'Olive oil'}], extras:[{n:'Extra mozzarella',p:50},{n:'Add mushrooms',p:40},{n:'Add pepperoni',p:60},{n:'Stuffed crust',p:60}] },
  { id:7,  cat:'pizza',  featured:false, name:'BBQ Chicken Pizza',      desc:'Smoky BBQ base, grilled chicken, red onion, sweetcorn & cheddar blend', price:500, tag:'🔥 Smoky & Bold', img:'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍕',n:'Pizza dough'},{e:'🥫',n:'BBQ sauce'},{e:'🍗',n:'Grilled chicken'},{e:'🧅',n:'Red onion'},{e:'🌽',n:'Sweetcorn'},{e:'🧀',n:'Cheddar'}], extras:[{n:'Extra chicken',p:70},{n:'Extra BBQ sauce',p:20},{n:'Jalapeños',p:20},{n:'Stuffed crust',p:60}] },
  { id:8,  cat:'pizza',  featured:false, name:'Four Cheese Pizza',      desc:'Cream base, mozzarella, cheddar, parmesan & gorgonzola with fresh thyme', price:560, tag:'🧀 Cheese Lover', img:'https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍕',n:'Thin crust'},{e:'🥛',n:'Cream base'},{e:'🧀',n:'Mozzarella'},{e:'🧀',n:'Cheddar'},{e:'🧀',n:'Parmesan'},{e:'🧀',n:'Gorgonzola'},{e:'🌿',n:'Thyme'}], extras:[{n:'Extra cheese',p:60},{n:'Add mushrooms',p:40},{n:'Honey drizzle',p:20}] },
  { id:9,  cat:'noodles',featured:false, name:'Spicy Beef Ramen',       desc:'Rich chilli broth, tender beef slices, ramen noodles, soft-boiled egg & spring onion', price:380, tag:'🌶 Spicy Kick', img:'https://images.pexels.com/photos/1731535/pexels-photo-1731535.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍜',n:'Ramen noodles'},{e:'🥩',n:'Beef slices'},{e:'🌶',n:'Chilli broth'},{e:'🥚',n:'Soft-boiled egg'},{e:'🧅',n:'Spring onion'},{e:'🫚',n:'Sesame oil'}], extras:[{n:'Extra beef',p:60},{n:'Extra egg',p:25},{n:'Extra spicy',p:10},{n:'Bamboo shoots',p:30}] },
  { id:10, cat:'noodles',featured:false, name:'Garlic Butter Pasta',    desc:'Al dente spaghetti tossed in golden garlic butter, aged parmesan & fresh herbs', price:320, tag:'🧄 Crowd Pleaser', img:'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍝',n:'Spaghetti'},{e:'🧄',n:'Roasted garlic'},{e:'🧈',n:'Butter'},{e:'🧀',n:'Aged parmesan'},{e:'🌿',n:'Fresh herbs'},{e:'🌑',n:'Black pepper'}], extras:[{n:'Add chicken',p:70},{n:'Add shrimp',p:90},{n:'Extra parmesan',p:30}] },
  { id:11, cat:'noodles',featured:false, name:'Stir-Fried Lo Mein',     desc:'Egg noodles wok-tossed with veggies, soy glaze & fresh ginger', price:360, tag:'🥢 Wok Fresh', img:'https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍜',n:'Egg noodles'},{e:'🥕',n:'Carrots'},{e:'🫑',n:'Bell peppers'},{e:'🧅',n:'Spring onion'},{e:'🫚',n:'Soy glaze'},{e:'🧄',n:'Fresh ginger'}], extras:[{n:'Add chicken',p:70},{n:'Add beef',p:80},{n:'Add tofu',p:50},{n:'Extra veggies',p:30}] },
  { id:12, cat:'noodles',featured:false, name:'Creamy Carbonara',       desc:'Silky egg & pecorino sauce, crispy pancetta, rigatoni & cracked black pepper', price:400, tag:'🍝 Italian Classic', img:'https://images.pexels.com/photos/5175537/pexels-photo-5175537.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍝',n:'Rigatoni'},{e:'🥚',n:'Egg yolk sauce'},{e:'🧀',n:'Pecorino romano'},{e:'🥓',n:'Pancetta'},{e:'🌑',n:'Black pepper'}], extras:[{n:'Extra pancetta',p:50},{n:'Extra parmesan',p:30},{n:'Add mushrooms',p:40}] },
  { id:13, cat:'sides',  featured:false, name:'Loaded Cheese Fries',    desc:'Crispy golden fries smothered in cheddar sauce, jalapeños & sour cream', price:200, tag:'🍟 Perfect Side', img:'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🍟',n:'Crispy fries'},{e:'🧀',n:'Cheddar sauce'},{e:'🌶',n:'Jalapeños'},{e:'🥛',n:'Sour cream'}], extras:[{n:'Extra cheese',p:30},{n:'Bacon bits',p:40}] },
  { id:14, cat:'sides',  featured:false, name:'Garden Side Salad',      desc:'Mixed greens, cherry tomatoes, cucumber, red onion & lemon vinaigrette', price:150, tag:'🥗 Fresh & Light', img:'https://images.pexels.com/photos/1059905/pexels-photo-1059905.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🥬',n:'Mixed greens'},{e:'🍅',n:'Cherry tomatoes'},{e:'🥒',n:'Cucumber'},{e:'🧅',n:'Red onion'},{e:'🍋',n:'Lemon dressing'}], extras:[{n:'Add chicken',p:70},{n:'Add feta',p:40},{n:'Extra dressing',p:20}] },
  { id:15, cat:'sides',  featured:false, name:'Fresh Mango Juice',      desc:'Cold-pressed Ethiopian mangoes — 100% fresh, zero sugar, zero water', price:100, tag:'🥭 100% Fresh', img:'https://images.pexels.com/photos/3625372/pexels-photo-3625372.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🥭',n:'Fresh mango'},{e:'🧊',n:'Ice'}], extras:[{n:'Add milk (smoothie)',p:30},{n:'Add honey',p:15}] },
  { id:16, cat:'sides',  featured:false, name:'Avocado Smoothie',       desc:'Creamy Ethiopian avocado blended with fresh milk & a hint of vanilla', price:120, tag:'💚 Local Fave', img:'https://images.pexels.com/photos/3727250/pexels-photo-3727250.jpeg?auto=compress&cs=tinysrgb&w=600', ings:[{e:'🥑',n:'Fresh avocado'},{e:'🥛',n:'Full-cream milk'},{e:'🍦',n:'Vanilla'},{e:'🧊',n:'Ice'}], extras:[{n:'Add honey',p:15},{n:'Larger size',p:30}] }
];

// Availability helpers
function getAv() { try { return JSON.parse(localStorage.getItem('ahadu_av') || '{}'); } catch(e) { return {}; } }
function setAv(o) { localStorage.setItem('ahadu_av', JSON.stringify(o)); }
function isAvail(id) { return getAv()[id] !== false; }
